test_size: 0.2
random_state: 42
fit_intercept: False
features:
  - year
  - plurality
  - apgar_5min
  - mother_age
  - father_age
  - gestation_weeks
  - ever_born
  # - mother_married
  - weight_pounds
